# Generated by Django 4.1.4 on 2023-01-21 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='user',
        ),
    ]
